# Generated by Django 3.1.2 on 2020-10-19 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillUpForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=63)),
                ('lastName', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=63)),
                ('state', models.CharField(max_length=63)),
                ('pincode', models.CharField(max_length=15)),
                ('Resume', models.FileField(upload_to='upload/resume/')),
                ('uniq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.joblist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
